 version: '3'
 services:
   node:
     build: 
       dockerfile: ./Dockerfile
       context: .
     image: node:16
     container_name: trybeclub_api
     tty: true
     stdin_open: true
     command: bash 
     restart: always
     working_dir: /app
     volumes:
       - ./:/app
     ports:
       - 3000:3000
     environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: trybeclub_db
      PORT: '3000'
     depends_on:
       - "database"
   database:
     container_name: trybeclub_db
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: trybeclub_db
     ports:
       - "33060:3306"
     volumes:
       - ./trybeclub_script.sql:/docker-entrypoint-initdb.d/trybeclub_script.sql
       - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf